# Generated by Django 3.2b1 on 2021-04-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_minamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
    ]
