# Generated by Django 3.2b1 on 2021-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=3),
        ),
    ]
